### PR TITLE
Amazon: Fix failing to obtain game library (#401)

### PR DESCRIPTION
**Pull request by darklinkpower**
- Fixes failing to obtain games during library update. (#401)
- While not needed, I added two missing parameters in the request body and updated the user agent for good measure.

### CODE REVIEW

**Comment by fthdgn** [comment]
https://github.com/JosefNemec/PlayniteExtensions/blob/d59a97d5bce1c35a55c7dc01000684169b76fd96/source/Libraries/AmazonGamesLibrary/Models/EntitlementsRequest.cs#L11

The official clients send "GetEntitlements" on "Operation" propery.

**Review by fthdgn — COMMENTED** [review]
Official client sends "GetEntitlements" instead of "GetEntitlementsV2"
        public string Operation = "GetEntitlementsV2";

**Comment by Indeep55** [comment]
Parece un error de amazon ya que launchbox, otro lanzador de juegos, tiene el mismo problema.

**Comment by fthdgn** [comment]
It was my first time do that. Maybe my method is not the best one.

I used mitmproxy.
I installed mitmproxy to my Raspberry Pi. And started it according to this documentation: https://docs.mitmproxy.org/stable/mitmproxytutorial-interceptrequests/

Then I started a clean Windows virtual machine by Hyper-V.
On network settings set the proxy to the IP of the Raspberry Pi.
Installed certificates according to this document:
https://docs.mitmproxy.org/stable/concepts-certificates/

Now all network request send from the Windows virtual machine will appear on the console of the Raspberry Pi.

The reason why I used Windows virtual machine is, installing third party root certificates are dangerous. It gives too much power to the issuer of the certificate.

**Pull request merged**
